remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: AIOSCPY
logo: /doc/images/aioscpy.png
description: 基于 asyncio + aiolibs 全家桶实现scrapy流程及标准的协程爬虫框架
show_downloads: true

github:
  zip_url: https://github.com/ihandmine/aioscpy/archive/refs/tags/0.3.12.zip
  tar_url: https://github.com/ihandmine/aioscpy/archive/refs/tags/0.3.12.tar.gz
  repository_url: https://github.com/ihandmine/aioscpy
  owner_url: https://github.com/ihandmine
  owner_url: ihandmine
  is_project_page: true
  ua_url: https://github.com/ihandmine/anti-useragent
  header_url: https://github.com/ihandmine/anti-header
  
